export const EMPLOYEE_FILTERS = {
  SHOW_ALL: "SHOW_ALL",
  GREATER_THAN_1000_USD: "GREATER_THAN_1000_USD",
  LESS_THAN_OR_EQUAL_1000_USD: "LESS_THAN_OR_EQUAL_1000_USD"
}

export const DEFAULT_DATEPICKER_OPTIONS = {
  foramt: JSCONSTANT.DATEPICKER_FORMAT,
  autoclose: true
}